disabled_rules: # rule identifiers turned on by default to exclude from running
  - trailing_whitespace
  - vertical_parameter_alignment
  - switch_case_alignment
  - todo

opt_in_rules:
  - unavailable_function
  - closure_spacing
  - discarded_notification_center_observer
  - discouraged_assert
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - fatal_error_message
  - file_name_no_space
  - function_default_parameter_at_end
  - ibinspectable_in_extension
  - identical_operands
  - legacy_multiple
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - override_in_extension
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - private_action
  - private_outlet
  - redundant_nil_coalescing
  - redundant_type_annotation
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - weak_delegate
  - yoda_condition

analyzer_rules:
  - unused_declaration
  - unused_import

file_length: 800
line_length: 280
function_body_length: 82
function_parameter_count: 8
cyclomatic_complexity: 16

identifier_name:
  min_length: 2
  max_length: 60
  allowed_symbols: [
    _
  ]
