name: Build RoyalVNC ObjC Demo

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build
    runs-on: macos-15

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Get Xcode Version
        run: xcodebuild -version

      - name: Build
        env:
          scheme: RoyalVNCObjCDemo
        run: xcodebuild clean build analyze -scheme "$scheme" | xcpretty && exit ${PIPESTATUS[0]}
